// plugin.mjs is generated by npm run build:oxlint; edit this typed source instead.
// oxlint-disable itrocks/declaration-order, itrocks/member-order -- Semantic order is intentional.
const LINE_WIDTH = 120;
const TAB_WIDTH = 2;
function alignmentEntry(line, lineNumber) {
    const indent = line.match(/^\t*/)?.[0] ?? '';
    const importMatch = line.match(/^(\t*import\s+.+?)(\s+)from\b/);
    if (importMatch) {
        const marker = line.indexOf('from', importMatch[1].length);
        return {
            actual: visualWidth(line.slice(0, marker)),
            indent,
            kind: 'from',
            line: lineNumber,
            natural: visualWidth(importMatch[1]) + 1
        };
    }
    const assignmentMatch = line.match(/^(\t*(?:const|let|var)\s+.+?)(\s*)=(?!=|>)/);
    if (assignmentMatch) {
        const marker = line.indexOf('=', assignmentMatch[1].length);
        return {
            actual: visualWidth(line.slice(0, marker)),
            indent,
            kind: '=',
            line: lineNumber,
            natural: visualWidth(assignmentMatch[1]) + 1
        };
    }
    const propertyMatch = line.match(/^(\t*(?:readonly\s+)?[A-Za-z_$][\w$]*\??:)(\s+)\S/);
    if (!propertyMatch)
        return;
    return {
        actual: visualWidth(propertyMatch[1] + propertyMatch[2]),
        indent,
        kind: ':',
        line: lineNumber,
        natural: visualWidth(propertyMatch[1]) + 1
    };
}
function checkAlignmentGroup(context, entries, lines) {
    if (entries.length < 2)
        return;
    const target = Math.max(...entries.map(entry => entry.natural));
    if (entries.some(entry => visualWidth(lines[entry.line - 1]) + target - entry.actual > LINE_WIDTH))
        return;
    for (const entry of entries) {
        if (entry.actual === target)
            continue;
        reportLine(context, entry.line, 0, lines[entry.line - 1].length, `Align ${entry.kind} with the adjacent declarations.`);
    }
}
function checkBraceLine(context, block, sameLine) {
    if (!block || !['BlockStatement', 'ClassBody', 'TSInterfaceBody'].includes(block.type))
        return;
    const previous = context.sourceCode.getTokenBefore(block);
    if (!previous)
        return;
    const isSameLine = previous.loc.end.line === block.loc.start.line;
    if (isSameLine === sameLine)
        return;
    context.report({
        message: sameLine
            ? 'Put this control-block opening brace on the control line.'
            : 'Put this opening brace on the next line.',
        node: context.sourceCode.getFirstToken(block)
    });
}
function checkClassPadding(context, node) {
    const body = node.body;
    if (!body || !Array.isArray(body.body) || !body.body.length)
        return;
    const lines = sourceLines(context.sourceCode.text);
    const opening = context.sourceCode.getFirstToken(body);
    const closing = context.sourceCode.getLastToken(body);
    if (lines[opening.loc.start.line]?.trim()) {
        context.report({ message: 'Leave one blank line after the class opening brace.', node: opening });
    }
    if (lines[closing.loc.start.line - 2]?.trim()) {
        context.report({ message: 'Leave one blank line before the class closing brace.', node: closing });
    }
}
function checkDeclarationSequence(context, nodes) {
    let previous;
    for (const node of nodes) {
        const current = declarationInfo(node);
        if (!current) {
            previous = undefined;
            continue;
        }
        if (previous && (current.rank < previous.rank)) {
            context.report({
                message: 'Group this declaration before declarations of the preceding kind.',
                node: current.node
            });
        }
        else if (previous
            && (current.rank === previous.rank)
            && current.name
            && previous.name
            && (compareNames(current.name, previous.name) < 0)) {
            context.report({ message: 'Sort declarations of the same kind alphabetically.', node: current.node });
        }
        previous = current;
    }
}
function checkFunctionSignature(context, node) {
    if (!node.params)
        return;
    const sourceCode = context.sourceCode;
    const tokens = sourceCode.getTokens(node);
    const openingIndex = tokens.findIndex(token => sourceCode.getText(token) === '(');
    if (openingIndex < 0)
        return;
    const arrowIndex = tokens.findIndex(token => sourceCode.getText(token) === '=>');
    if ((arrowIndex >= 0) && (openingIndex > arrowIndex))
        return;
    let depth = 0;
    let closingIndex = -1;
    for (let index = openingIndex; index < tokens.length; index++) {
        const text = sourceCode.getText(tokens[index]);
        if (text === '(')
            depth++;
        if (text === ')')
            depth--;
        if (!depth) {
            closingIndex = index;
            break;
        }
    }
    if (closingIndex < 0)
        return;
    const opening = tokens[openingIndex];
    const closing = tokens[closingIndex];
    const afterClosing = tokens[closingIndex + 1];
    const returnColon = afterClosing && (sourceCode.getText(afterClosing) === ':') ? afterClosing : undefined;
    if (opening.loc.start.line === closing.loc.start.line) {
        checkSingleLineSignatureReturn(context, closing, returnColon, node);
        return;
    }
    const lines = sourceLines(sourceCode.text);
    if (lines[opening.loc.end.line - 1].slice(opening.loc.end.column).trim()) {
        context.report({ message: 'Break immediately after the opening parenthesis.', node: opening });
    }
    if (lines[closing.loc.start.line - 1].slice(0, closing.loc.start.column).trim()) {
        context.report({ message: 'Put the closing parenthesis on its own indentation.', node: closing });
    }
    if (returnColon && (returnColon.loc.start.line !== closing.loc.start.line)) {
        context.report({ message: 'Keep ): ReturnType together on one line.', node: returnColon });
    }
    const previous = tokens[closingIndex - 1];
    if (previous && (sourceCode.getText(previous) === ',')) {
        context.report({ message: 'Omit the trailing parameter comma.', node: previous });
    }
    const parameterLines = node.params.map(parameter => parameter.loc.start.line);
    const allOnOneLine = parameterLines.every(line => line === parameterLines[0]);
    if (!allOnOneLine && (new Set(parameterLines).size !== parameterLines.length)) {
        context.report({ message: 'Put either all parameters on one line or one parameter per line.', node });
    }
}
function checkKeywordNewLine(context, preceding, keyword, name) {
    if (!keyword)
        return;
    const closing = context.sourceCode.getLastToken(preceding);
    if (closing.loc.end.line !== keyword.loc.start.line)
        return;
    context.report({ message: `Put ${name} on a new line after the preceding closing brace.`, node: keyword });
}
function checkSingleLineSignatureReturn(context, closing, returnColon, node) {
    if (!returnColon || (returnColon.loc.start.line === closing.loc.start.line))
        return;
    const source = context.sourceCode.text;
    const lines = sourceLines(source);
    const prefix = lines[closing.loc.end.line - 1].slice(0, closing.loc.end.column);
    const body = node.body;
    const signatureEnd = body?.range[0] ?? node.range[1];
    const returnText = source.slice(returnColon.range[0], signatureEnd).replace(/\s+/g, ' ').trim();
    if (visualWidth(prefix + returnText) > LINE_WIDTH)
        return;
    context.report({
        message: 'Keep the return type on the signature line while the signature fits within 120 columns.',
        node: returnColon
    });
}
function compareNames(left, right) {
    return left.localeCompare(right, 'en');
}
function declarationInfo(node) {
    if ((node.type === 'ExportNamedDeclaration') && node.declaration)
        node = node.declaration;
    const typeRanks = {
        TSInterfaceDeclaration: 0,
        TSTypeAliasDeclaration: 0
    };
    if (node.type in typeRanks)
        return { name: node.id?.name ?? '', node, rank: 0 };
    if (node.type === 'VariableDeclaration') {
        const declaration = node.declarations?.[0];
        const kind = node.kind;
        return { name: declaration?.id?.name ?? '', node, rank: kind === 'const' ? 1 : 2 };
    }
    if (['FunctionDeclaration', 'TSDeclareFunction'].includes(node.type)) {
        return { name: node.id?.name ?? '', node, rank: 3 };
    }
    if (node.type === 'ClassDeclaration')
        return { name: node.id?.name ?? '', node, rank: 4 };
}
function importKey(node) {
    const module = typeof node.source?.value === 'string' ? node.source.value : '';
    const symbols = (node.specifiers ?? []).map(specifier => {
        const imported = specifier.type === 'ImportSpecifier' ? specifier.imported : undefined;
        return imported?.name ?? specifier.local?.name ?? '';
    });
    return module + '\0' + symbols.join('\0');
}
function lineLocation(line, start, end) {
    return {
        end: { column: end, line },
        start: { column: start, line }
    };
}
function multilineTokenLines(sourceCode, node) {
    const lines = new Set();
    for (const token of sourceCode.getTokens(node, { includeComments: true })) {
        for (let line = token.loc.start.line + 1; line <= token.loc.end.line; line++)
            lines.add(line);
    }
    return lines;
}
function nodeName(node) {
    if (node.key?.name)
        return node.key.name;
    if (typeof node.key?.value === 'string')
        return node.key.value;
    if (node.id?.name)
        return node.id.name;
    return '';
}
function reportLine(context, line, start, end, message) {
    context.report({ loc: lineLocation(line, start, end), message });
}
function rule(description, create) {
    return {
        create,
        meta: {
            docs: { description },
            schema: [],
            type: 'layout'
        }
    };
}
function sourceLines(source) {
    return source.split(/\r?\n/);
}
function visualWidth(text) {
    let width = 0;
    for (const character of text)
        width += character === '\t' ? TAB_WIDTH : 1;
    return width;
}
const alignmentRule = rule('Align adjacent related declarations.', context => ({
    Program() {
        const lines = sourceLines(context.sourceCode.text);
        let group = [];
        for (let index = 0; index <= lines.length; index++) {
            const entry = index < lines.length ? alignmentEntry(lines[index], index + 1) : undefined;
            if (entry
                && (!group.length || ((entry.line === group[group.length - 1].line + 1)
                    && (entry.kind === group[0].kind)
                    && (entry.indent === group[0].indent)))) {
                group.push(entry);
                continue;
            }
            checkAlignmentGroup(context, group, lines);
            group = entry ? [entry] : [];
        }
    }
}));
const braceStyleRule = rule('Apply the it.rocks hybrid brace style.', context => ({
    ArrowFunctionExpression() {
    },
    ClassDeclaration(node) {
        checkBraceLine(context, node.body, false);
    },
    ClassExpression(node) {
        checkBraceLine(context, node.body, false);
    },
    DoWhileStatement(node) {
        checkBraceLine(context, node.body, true);
    },
    ForInStatement(node) {
        checkBraceLine(context, node.body, true);
    },
    ForOfStatement(node) {
        checkBraceLine(context, node.body, true);
    },
    ForStatement(node) {
        checkBraceLine(context, node.body, true);
    },
    FunctionDeclaration(node) {
        checkBraceLine(context, node.body, false);
    },
    FunctionExpression(node) {
        checkBraceLine(context, node.body, false);
    },
    IfStatement(node) {
        const consequent = node.consequent;
        const alternate = node.alternate;
        checkBraceLine(context, consequent, true);
        checkBraceLine(context, alternate, true);
        if (alternate && consequent) {
            checkKeywordNewLine(context, consequent, context.sourceCode.getTokenAfter(consequent), 'else');
        }
    },
    SwitchStatement(node) {
        const tokens = context.sourceCode.getTokens(node);
        const opening = tokens.find(token => context.sourceCode.getText(token) === '{');
        if (!opening)
            return;
        const previous = context.sourceCode.getTokenBefore(opening);
        if (previous && (previous.loc.end.line !== opening.loc.start.line)) {
            context.report({ message: 'Put this switch opening brace on the control line.', node: opening });
        }
    },
    TSInterfaceDeclaration(node) {
        checkBraceLine(context, node.body, false);
    },
    TryStatement(node) {
        const block = node.block;
        const handler = node.handler;
        const finalizer = node.finalizer;
        checkBraceLine(context, block, true);
        if (handler) {
            const handlerBody = handler.body;
            checkBraceLine(context, handlerBody, true);
            checkKeywordNewLine(context, block, context.sourceCode.getTokenAfter(block), 'catch');
        }
        if (finalizer) {
            const preceding = handler ?? block;
            checkBraceLine(context, finalizer, true);
            checkKeywordNewLine(context, preceding, context.sourceCode.getTokenAfter(preceding), 'finally');
        }
    },
    WhileStatement(node) {
        checkBraceLine(context, node.body, true);
    },
    WithStatement(node) {
        checkBraceLine(context, node.body, true);
    }
}));
const classPaddingRule = rule('Keep blank lines at class body boundaries.', context => ({
    ClassDeclaration(node) {
        checkClassPadding(context, node);
    },
    ClassExpression(node) {
        checkClassPadding(context, node);
    }
}));
const declarationOrderRule = rule('Order independent declarations by kind and name.', context => ({
    BlockStatement(node) {
        if (Array.isArray(node.body))
            checkDeclarationSequence(context, node.body);
    },
    Program(node) {
        if (Array.isArray(node.body))
            checkDeclarationSequence(context, node.body);
    }
}));
const functionSignatureRule = rule('Apply the it.rocks function signature layouts.', context => ({
    ArrowFunctionExpression(node) {
        checkFunctionSignature(context, node);
    },
    FunctionDeclaration(node) {
        checkFunctionSignature(context, node);
    },
    FunctionExpression(node) {
        checkFunctionSignature(context, node);
    },
    TSDeclareFunction(node) {
        checkFunctionSignature(context, node);
    }
}));
const indentationRule = rule('Use tabs for indentation.', context => ({
    Program(node) {
        const lines = sourceLines(context.sourceCode.text);
        const ignoredLines = multilineTokenLines(context.sourceCode, node);
        for (let index = 0; index < lines.length; index++) {
            if (ignoredLines.has(index + 1))
                continue;
            const indentation = lines[index].match(/^[ \t]+(?=\S)/)?.[0];
            if (!indentation || !indentation.startsWith(' '))
                continue;
            reportLine(context, index + 1, 0, indentation.length, 'Indent with tabs; reserve spaces for alignment.');
        }
    }
}));
const lineLengthRule = rule('Limit lines to 120 columns with tabs counted as two.', context => ({
    Program(node) {
        const lines = sourceLines(context.sourceCode.text);
        const tokens = context.sourceCode.getTokens(node, { includeComments: true });
        for (let index = 0; index < lines.length; index++) {
            const line = lines[index];
            if (visualWidth(line) <= LINE_WIDTH)
                continue;
            const indivisible = tokens.some(token => ((token.loc.start.line === index + 1)
                && (token.loc.end.line === index + 1)
                && (visualWidth(context.sourceCode.getText(token)) > LINE_WIDTH)));
            if (indivisible)
                continue;
            reportLine(context, index + 1, 0, line.length, 'Limit this line to 120 columns; each tab counts as two.');
        }
    }
}));
const memberOrderRule = rule('Sort independent members alphabetically.', context => ({
    ClassBody(node) {
        if (!Array.isArray(node.body))
            return;
        let previous = '';
        for (const member of node.body) {
            const name = nodeName(member);
            if (!name || (name === 'constructor')) {
                previous = '';
                continue;
            }
            if (previous && (compareNames(name, previous) < 0)) {
                context.report({ message: 'Sort independent class members alphabetically.', node: member });
            }
            previous = name;
        }
    },
    ObjectExpression(node) {
        const properties = node.properties ?? [];
        let previous = '';
        for (const property of properties) {
            if (property.type === 'SpreadElement') {
                previous = '';
                continue;
            }
            const name = nodeName(property);
            if (!name) {
                previous = '';
                continue;
            }
            if (previous && (compareNames(name, previous) < 0)) {
                context.report({ message: 'Sort independent object properties alphabetically.', node: property });
            }
            previous = name;
        }
    },
    TSInterfaceBody(node) {
        if (!Array.isArray(node.body))
            return;
        let previous = '';
        for (const member of node.body) {
            const name = nodeName(member);
            if (!name) {
                previous = '';
                continue;
            }
            if (previous && (compareNames(name, previous) < 0)) {
                context.report({ message: 'Sort interface members alphabetically.', node: member });
            }
            previous = name;
        }
    }
}));
const moduleOrderRule = rule('Keep imports first and sort them by module then symbol.', context => ({
    Program(node) {
        if (!Array.isArray(node.body))
            return;
        let foundDeclaration = false;
        let previousKey = '';
        for (const statement of node.body) {
            if (statement.type !== 'ImportDeclaration') {
                foundDeclaration = true;
                continue;
            }
            if (foundDeclaration)
                context.report({ message: 'Keep imports before other declarations.', node: statement });
            if (!statement.specifiers?.length) {
                previousKey = '';
                continue;
            }
            const key = importKey(statement);
            if (previousKey && (compareNames(key, previousKey) < 0)) {
                context.report({ message: 'Sort imports by module then imported symbol.', node: statement });
            }
            previousKey = key;
        }
    }
}));
const postfixSpacingRule = rule('Put one space before postfix increment and decrement operators.', context => ({
    UpdateExpression(node) {
        const update = node;
        if (update.prefix)
            return;
        const operator = context.sourceCode.getLastToken(node);
        const before = context.sourceCode.text.slice(operator.range[0] - 1, operator.range[0]);
        if (/\s/.test(before))
            return;
        context.report({ message: 'Put a space before this postfix operator.', node: operator });
    }
}));
const quotesRule = rule('Use single quotes for string literals.', context => ({
    Program(node) {
        for (const token of context.sourceCode.getTokens(node)) {
            const text = context.sourceCode.getText(token);
            if (!text.startsWith('"') || !text.endsWith('"'))
                continue;
            context.report({ message: 'Use single quotes for this string literal.', node: token });
        }
    }
}));
const semicolonsRule = rule('Omit semicolons when automatic semicolon insertion is safe.', context => {
    const mandatory = new Set();
    return {
        EmptyStatement(node) {
            mandatory.add(node.range[0]);
        },
        ForStatement(node) {
            const tokens = context.sourceCode.getTokens(node);
            let braces = 0;
            let brackets = 0;
            let parentheses = 0;
            for (const token of tokens) {
                const text = context.sourceCode.getText(token);
                if (text === '(')
                    parentheses++;
                if (text === '[')
                    brackets++;
                if (text === '{')
                    braces++;
                if ((text === ';') && (parentheses === 1) && !brackets && !braces)
                    mandatory.add(token.range[0]);
                if (text === ')') {
                    parentheses--;
                    if (!parentheses)
                        break;
                }
                if (text === ']')
                    brackets--;
                if (text === '}')
                    braces--;
            }
        },
        'Program:exit'(node) {
            const source = context.sourceCode.text;
            const lines = sourceLines(source);
            for (const token of context.sourceCode.getTokens(node)) {
                if (context.sourceCode.getText(token) !== ';')
                    continue;
                if (mandatory.has(token.range[0]))
                    continue;
                const line = lines[token.loc.start.line - 1];
                const before = line.slice(0, token.loc.start.column);
                const after = line.slice(token.loc.end.column);
                if (!before.trim())
                    continue;
                if (after.replace(/\/\/.*$/, '').trim())
                    continue;
                const next = context.sourceCode.getTokenAfter(token);
                if (next
                    && (next.loc.start.line > token.loc.end.line)
                    && '([`+-/.?<>'.includes(context.sourceCode.getText(next)[0]))
                    continue;
                context.report({ message: 'Omit this semicolon; ASI is safe here.', node: token });
            }
        }
    };
});
export default {
    meta: {
        name: 'itrocks'
    },
    rules: {
        alignment: alignmentRule,
        'brace-style': braceStyleRule,
        'class-padding': classPaddingRule,
        'declaration-order': declarationOrderRule,
        'function-signature': functionSignatureRule,
        indentation: indentationRule,
        'line-length': lineLengthRule,
        'member-order': memberOrderRule,
        'module-order': moduleOrderRule,
        'postfix-spacing': postfixSpacingRule,
        quotes: quotesRule,
        semicolons: semicolonsRule
    }
};
